spring.application.name=assistant-rh-api
spring.datasource.url=jdbc:postgresql://localhost:5433/assistant_rh
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

gemini.api.key=${GEMINI_API_KEY:}

# Encodage UTF-8 des réponses HTTP
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
